### ISSUE TITLE
Consideration of Patch Management EAs

### ISSUE THREAD

**Issue by aduffner** [ninxsoft/Kmart#1]
First of all, great tool you have created here! 💯 

May Extension attributes _created automatically by patch management_ appear here incorrectly: mac_extension_attributes_not_linked

But I think this is a limitation of Jamf Pro, as I haven't found a way to retrieve this info via Classic API or the newer Universal API.

**Comment by ninxsoft** [comment]
Having a poke around with a **Classic** and **Universal** APIs, I also cannot seem to find a clever way to detect if an Extension Attribute is being used by **Patch Management Software Title**.

The closest thing I can think of is the default Extension Attribute  **description** that gets generated, however that can be changed very easily and would cause inaccuracies.

🤔

**Comment by redshirtdave** [comment]
not ideal, but could just do a report indicating that it's probably a jamf patch ea based on jamf naming conventions, which are:

- 'jamf-patch-<title>' (new mondada version)
- 'patch-EA-<title>' (old legacy version)

**Comment by aduffner** [comment]
As @ninxsoft created https://github.com/ninxsoft/Kmart/issues/3 i will close my issue now.
