### ISSUE TITLE
Linting of Python scripts 

### ISSUE THREAD

**Issue by ninxsoft** [ninxsoft/Kmart#12]
Kmart currently only supports linting **sh/bash/dash/ksh** scripts via [Shellcheck](https://github.com/koalaman/shellcheck).

Look into adding support for Python linter(s), possibly (preferably?) [flake8](https://github.com/PyCQA/flake8)

**Comment by smithjw** [comment]
Would be great if Shellcheck supported `zsh`

**Comment by ninxsoft** [comment]
I agree - https://github.com/koalaman/shellcheck/issues/809
