### ISSUE TITLE
Mac Extension Attributes

### ISSUE THREAD

**Issue by danielnovello** [ninxsoft/Kmart#2]
Wonderful piece of software, thank you so much!
I am seeing an issue with the Mac Extension Attributes.

Error for all items:

`Literal carriage return. Run script through tr -d 'r' .`

Thanks

**Comment by danielnovello** [comment]
My mistake

**Comment by ninxsoft** [comment]
😃

You probably figured it out - `shellcheck` is complaining about the carriage return character:

https://github.com/koalaman/shellcheck/wiki/SC1017

Pretty common if parts of the script have been copied (in my experience, usually from one text-editor to another with different settings).

You favourite text editor (ie. Atom, Visual Studio Code) should have some built-in function to strip out these characters.

`tr -d '\r' < script.sh   > fixed_script.sh` will also get the job done 👍
