### ISSUE TITLE
Mac Policies No Payload

### ISSUE THREAD

**Issue by monodata** [ninxsoft/Kmart#23]
I'm trying to get a report of mac policies with no payload but despite marking it as true in the json config, it never reports anything.

`"mac_policies_no_payload": true,`

I have several other items enabled and they report ok but just not the 'mac policies no payload'.

**Comment by ninxsoft** [comment]
@monodata thanks for bringing this to my attention - looks like I had a bug in the `mac_policies_no_payload` report logic.

This is now fixed: 082cd80a7ac61682ac15c616af9c021795a95bec
