### ISSUE TITLE
URL changes in Jamf 10.42

### ISSUE THREAD

**Issue by thomasrmartin** [ninxsoft/Kmart#25]
With the Jamf settings page changes, some of the URLs in Kmart reports are now incorrect. There may be others but the two I'm finding are:

Scripts: old url- https://mydomain.jamfcloud.com/view/settings/computer/scripts, new url- https://mydomain.jamfcloud.com/view/settings/computer-management/scripts.

Departments: old url- https://mydomain.jamfcloud.com//view/settings/network/departments, new url- https://mydomain.jamfcloud.com/view/settings/network-organization/departments

**Comment by ninxsoft** [comment]
@thomasrmartin thanks for the assist - the URLs for Buildings, Departments and Scripts are now correct: af267564c729d4bd902cb8ae7528c1a425c42646
