### ISSUE TITLE
Various reports include unmanaged devices

### ISSUE THREAD

**Issue by ozpinbeacon** [ninxsoft/Kmart#6]
Reports such as mac_devices_last_check_in include devices which are unmanaged in Jamf

**Comment by ninxsoft** [comment]
* `mac_devices_last_check_in`, `mac_devices_last_inventory` and `mobile_devices_last_inventory` now exclude managed devices.
* Also added `mac_devices_unmanaged` and `mobile_devices_unmanaged` reports.

**Comment by ozpinbeacon** [comment]
Thanks! Appreciate it!
